//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingDealMethod
    {
        public int ListingId { get; set; }
        public int DealMethodId { get; set; }
        public string Description { get; set; }
    
        public virtual Listing Listing { get; set; }
    }
}
