//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingType
    {
        public ListingType()
        {
            this.ListingPurchaseLogs = new HashSet<ListingPurchaseLog>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string GroupCode { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public int Duration { get; set; }
        public Nullable<int> sort { get; set; }
    
        public virtual ICollection<ListingPurchaseLog> ListingPurchaseLogs { get; set; }
    }
}
