//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        public Listing()
        {
            this.ListingDealMethods = new HashSet<ListingDealMethod>();
            this.ListingImages = new HashSet<ListingImage>();
        }
    
        public int id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsNegotiable { get; set; }
        public Nullable<int> ContactMethod { get; set; }
        public Nullable<int> LocationId { get; set; }
        public int Status { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual RefCategory RefCategory { get; set; }
        public virtual RegionZone RegionZone { get; set; }
        public virtual ICollection<ListingDealMethod> ListingDealMethods { get; set; }
        public virtual ICollection<ListingImage> ListingImages { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
