//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingPurchaseLog
    {
        public int Id { get; set; }
        public Nullable<int> ListingId { get; set; }
        public string ListingTypeCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ListingType ListingType { get; set; }
        public virtual Listing Listing { get; set; }
    }
}
