//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefTable
    {
        public RefTable()
        {
            this.TemplateTypes = new HashSet<TemplateType>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Val { get; set; }
        public string Val2 { get; set; }
        public string Val3 { get; set; }
        public string Type { get; set; }
        public string ParentCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Sort { get; set; }
    
        public virtual ICollection<TemplateType> TemplateTypes { get; set; }
    }
}
