//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionZone
    {
        public RegionZone()
        {
            this.Listings = new HashSet<Listing>();
            this.Listings1 = new HashSet<Listing>();
        }
    
        public int id { get; set; }
        public int RegionId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<double> Lng { get; set; }
        public Nullable<double> Lat { get; set; }
        public string Name { get; set; }
        public Nullable<double> Sort { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<Listing> Listings { get; set; }
        public virtual ICollection<Listing> Listings1 { get; set; }
    }
}
