//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateType
    {
        public string Code { get; set; }
        public string ListType { get; set; }
        public string TemplateName { get; set; }
    
        public virtual RefTable RefTable { get; set; }
    }
}
